using AITaskAgent.LLM.Constants;

namespace AITaskAgent.LLM.Models;

/// <summary>
/// A single choice or variant generated by the LLM.
/// Used when the model is requested to generate multiple candidates.
/// </summary>
public sealed class LlmChoice
{
    /// <summary>The sequence index of this choice.</summary>
    public int Index { get; init; }

    /// <summary>The generated content for this choice.</summary>
    public required string Content { get; init; }

    /// <summary>Tool calls requested in this choice.</summary>
    public List<ToolCall>? ToolCalls { get; init; }

    /// <summary>Normalized finish reason.</summary>
    public FinishReason? FinishReason { get; init; }

    /// <summary>Provider-specific finish reason string.</summary>
    public string? RawFinishReason { get; init; }
}
