namespace Samples.AdvancedLlmPipeline;

/// <summary>
/// Represents the drafts generated by parallel writers.
/// </summary>
public sealed record WriterResults
{
    /// <summary>
    /// Gets or sets the draft from the first writer.
    /// </summary>
    public string Draft1 { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the draft from the second writer.
    /// </summary>
    public string Draft2 { get; set; } = string.Empty;
}
